# Generated by Django 4.0.6 on 2022-11-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apis',
            name='content',
        ),
    ]
