# Generated by Django 4.0.6 on 2022-11-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_apis_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIs',
            new_name='Image',
        ),
    ]
