# Generated by Django 4.0.6 on 2022-11-20 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_rename_apis_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=16)),
                ('mobile_phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Delivery Detail',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('delivery_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.deliverydetail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.AlterModelTable(
            name='image',
            table='Product Images',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Adidas', 'Adidas'), ('Blundstone', 'Blundstone'), ('Birkenstock', 'Birkenstock'), ('Crocs', 'Crocs'), ('Columbia', 'Columbia'), ('Diadora', 'Diadora'), ('DC Shoes', 'DC Shoes'), ('Dr. Martens', 'Dr. Martens'), ('ECCO', 'ECCO'), ('Geox', 'Geox'), ('New Balance', 'New Balance'), ('Nike', 'Nike'), ('Saucony', 'Saucony'), ('Skechers', 'Skechers'), ('Vans', 'Vans'), ('Puma', 'Puma'), ('Converse', 'Converse'), ('Reebok', 'Reebok'), ('Timberland', 'Timberland')], max_length=50)),
                ('gender_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(choices=[('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=2)),
                ('type', models.CharField(choices=[('Sandals', 'Sandals'), ('Shoes', 'Shoes'), ('Sneakers', 'Sneakers'), ('Boots', 'Boots')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('count_in_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.image')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
            options={
                'db_table': 'Orders Detail',
            },
        ),
    ]
